repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        require_serial: true
        language: python
        minimum_pre_commit_version: 2.9.2
        types_or: [python, pyi]
      - id: flake8
        name: flake8
        description: '`flake8` is a command-line utility for enforcing style consistency across Python projects.'
        entry: flake8
        language: python
        types: [python]
        require_serial: true
      - id: isort
        name: isort
        entry: isort
        require_serial: true
        language: python
        language_version: python3
        types_or: [cython, pyi, python]
        args: ['--filter-files']
        minimum_pre_commit_version: '2.9.2'
      